examples/contracts/llm-erc20.py

Added intelligent contract for LLM erc20 token example

78-simulator---implement-use-case-example-for-a-contract-that-only-uses-the-llm-to-compute-the-state-transitions

---

README.md
frontend/src/components/Tutorial/TutorialContainer.vue
frontend/src/components/Tutorial/wizard_of_coin.py
frontend/src/views/Simulator/RunDebugView.vue

Fixed the tutorial example.
Adapted the tutorial to the new syntax

148-simulator: fix-tutorial-contract?expand=1

---

docker-compose.yml
docker/Dockerfile.genvm
docker/Dockerfile.rpc

The changes in the docker files regarding the debugger setup have been reverted because it fails on some platforms.

Test docker revert

---

CONTRIBUTING.md
frontend/src/components/SimulatorMenu.vue
frontend/src/constants/links.ts

NOTE: there are some formatting changes. The relevant commit is here: https://github.com/yeagerai/genlayer-simulator/pull/189/commits/508bfc4a7ee4711246e3fd4dfe76d2a14eea2e35
- Centralized helper links
- Fixed the target for discord and documents

188 sim   fix discord and docs links

---

frontend/src/components/Simulator/HomeTab.vue

- Change "Code in Python" to "Internet Access"

fix: home screen

---

frontend/src/views/Simulator/RunDebugView.vue

#171 => Fix to run e2e test in contract examples

171 Simulator - e2e frontend tests for contract examples - fixes

---

frontend/src/views/Simulator/SettingsView.vue

Added required fields when create and update validators

224 SIM-Create and Edit validator: make provider, model, and stake fields mandatory

---

examples/contracts/football_prediction_market.py

Mitigation for https://github.com/yeagerai/genlayer-simulator/issues/267
By improving the wording on the example, LLMs are less prone to make mistakes

improvement: improve llm handling of strings

---

.github/pull_request_template.md

Fixes #291
Signed-off-by: Agustín Ramiro Díaz <agustin.ramiro.diaz@gmail.com>

291-sim-propose-a-pr-template

---

.github/workflows/backend_integration_tests_pr.yml
backend/database_handler/transactions_processor.py

Fixes https://github.com/yeagerai/genlayer-simulator/issues/303
- Does the necessary indexing in an array
- to fix a bug while deploying a contract
- manually created contracts
- ran e2e tests locally
Fixed a bug when deploying a smart contract

SIM-Transaction indexing problem

---

backend/database_handler/db_client.py
backend/database_handler/models.py
backend/database_handler/validators_registry.py

Part of #306
Uses SQLAlchemy engine and session in validator retrieval from db
- to set an example on how we can improve the db handler
- ran e2e tests
This is a small example, the objective is to slowly move towards this pattern
Check out the docs http://docs.sqlalchemy.org/

SIM-BE-Use SQLAlchemy instead of handcrafted SQL Queries

---

.github/workflows/backend_integration_tests_pr.yml
tests/common/request.py
tests/integration/test_football_prediction_market.py
webrequest/request.py

Fixes https://github.com/yeagerai/genlayer-simulator/issues/328
check out my review
- to fix a e2e tests
https://github.com/yeagerai/genlayer-simulator/actions/runs/10079441879/job/27866777834
check my review
Do not review commit history

SIM-E2E-Fix Selenium issue

---

.github/workflows/backend_integration_tests_pr.yml
backend/database_handler/validators_registry.py
backend/node/create_nodes/create_nodes.py
backend/node/genvm/llms.py
backend/protocol_rpc/configuration.py
backend/protocol_rpc/endpoints.py
backend/protocol_rpc/server.py

Fixes #309
- adds global configuration struct in top module
- adds `get_ollama_url` as configuration to required functions
- this also serves as dependency injection, functions behave as interfaces (some call it the [strategy pattern](https://fsharpforfunandprofit.com/posts/convenience-functions-as-interfaces/))
described in issue
- I've ran e2e tests locally
Only example demonstration, no big refactor

SIM-BE-Decouple configuration

---

.github/workflows/backend_integration_tests_pr.yml
.github/workflows/unit-tests-pr.yml

Fixes en error introduced in https://github.com/yeagerai/genlayer-simulator/pull/333
Error explanation: GitHub outputs seem to be treated as strings, not booleans :face_exhaling:

Hotfix: GH Action Test triggers

---

.github/workflows/scan-codeql.yml

This PR adds a GitHub Actions workflow to run CodeQL code scanning on the repository.
CodeQL is a powerful static analysis tool that can help us identify potential security vulnerabilities and code quality issues early in the development process. This proactive approach will help us maintain a more secure and reliable codebase.
Build run: https://github.com/yeagerai/genlayer-simulator/actions/runs/10093701422
- The workflow successfully runs CodeQL analysis on both Python and JS code within the repository.
- No breaking changes were introduced by the addition of this workflow.

Add CodeQL scanning

---

.github/workflows/test-semgrep.yml

- Added static code scanning(SAST) with Semgrep OSS
To improve the quality and security of the code. Find vulnerabilities.
https://github.com/yeagerai/genlayer-simulator/actions/runs/10093296563/job/27908703416
Same like in the points system repo:
https://github.com/yeagerai/genlayer-points-system/actions/workflows/test-semgrep.yml

Added SAST scans with Semgrep

---

.github/workflows/.pre-commit.yml
.github/workflows/load-test-oha.yml
.pre-commit-config.yaml
CONTRIBUTING.md
backend/database_handler/migration/versions/188ca1c3a340_add_transactions_audit_table_and_.py
backend/node/create_nodes/defaults.json
backend/node/create_nodes/nodes.json
backend/node/create_nodes/test_create_nodes.py
backend/node/genvm/equivalence_principle.py
backend/node/genvm/std/vector_store.py
docker/Dockerfile.frontend
examples/contracts/llm_erc20.py
examples/contracts/log_indexer.py
frontend/postcss.config.cjs
frontend/scripts/contract-examples.js
frontend/shims.d.ts
frontend/src/components/JsonViewer/icon.svg
frontend/src/components/JsonViewer/types/json-regexp.vue
frontend/src/components/Simulator/ContractState.vue
frontend/src/views/Simulator/RunDebugView.vue
frontend/test/e2e/CreateNodeValidator.spec.ts
frontend/test/e2e/Tutorial.spec.ts
frontend/test/pages/BasePage.ts
frontend/test/pages/RunDebugPage.ts
frontend/test/pages/TutorialPage.ts
frontend/tsconfig.node.json
frontend/tsconfig.vitest.json
requirements.txt
tests/integration/test_log_indexer.py

Fixes https://github.com/yeagerai/genlayer-simulator/issues/348
- added `precommit` hooks for linting and backend unit tests 
- added a GH action to run `pre-commit`
- given that pre-commit is opt-in, I think it's a good idea to check if the conventions are being followed
- to force developers to apply standards before committing, reducing the time spent on discussions around these details
- I've made commits and I've checked that the pre-commit hooks were working
- pre-commit needed was added as a dev dependency, it is installed with Python (documented in `Contributing.md`)
- installing npm packages was added as dev dependencies for the frontend commits
The other alternative I thought of would be to use Docker to not use `pre-commit` (or the other dependencies). I didn't think it made …

348 sim be add precommit hooks for testing code linting and other conventions

---

.github/workflows/scan-codeql.yml

Fixes #363
- Fixes CodeQL scan action
- to fix a bug
https://github.com/yeagerai/genlayer-simulator/actions/runs/10298453094

363-SIM-Fixing-CodeQL-action

---

frontend/src/components/Simulator/ConstructorParameters.vue
frontend/src/components/Simulator/ContractsPanel.vue
frontend/src/components/Simulator/NodeLogs.vue
frontend/src/hooks/useContractQueries.ts
frontend/src/stores/contracts.ts
frontend/src/stores/tutorial.ts

Fixes #255 
- Added an error notice overlaying the editor when syntax errors occur
- Improve development experience
- tested the new feature
- For now a simple notice, in the future we can do highlight + tooltip
- Added an error notice for code errors

255 sim editor errors

---

frontend/src/components/Simulator/ModalSection.vue
frontend/src/components/Simulator/TransactionItem.vue
frontend/src/components/global/ConfirmationModal.vue

Fixes #374 
Fixes #373 
- Improved the UI of transactions
- Improve user experience
- lint
- format
- Added a "section" component to use in modals
Probably would be good to test various cases of tx failure, etc. and make sure it displays properly in each case.
- Improved Transaction details UI

374 sim improve transactions info in the details modal

---

.github/workflows/release-from-main.yml
backend/database_handler/validators_registry.py
backend/protocol_rpc/endpoints.py

Fixes #384 
- Fixes the error found when deleting a validator
- Reordered and organized endpoints better
- Removed an unused endpoint for counting validators
- Fix the bug
- Take the opportunity to clean a little bit without changing the behaviour
- General test to check main features
- Tested the bug fix
Reorder and reorganize the endpoints
This is the real fix: a611ffdcc02f4f0fc4a3bfcb8b6606236addf734
Fixed a bug that prevented validators to be removed properly

384 sim fix delete validator endpoint

---

backend/consensus/base.py

Partially fixes https://github.com/yeagerai/genlayer-simulator/issues/387
- Adds a check before executing transactions to see if the transaction is in the Pending state
- we have a toctou issue in how we handle the transactions. Fixing this is crucial to improve behavior
- tested the fix
- tested many other contracts to check behavior
- I've also modified some Python code (without changes in behavior) while debugging to reduce cognitive complexity. I've left the changes in the PR
- This is not the full fix, but it doesn't make sense to do a full refactor to fix it since transactions' processing will change in the near future. Also, I'd like this to be out for the hackathon
The actual fix is in `exec_transaction`
Fixed a bug where transactions were re-executing when validating was slow

387 SIM-Infinite transaction loop

---

backend/consensus/base.py
backend/node/base.py
backend/node/genvm/base.py
backend/protocol_rpc/endpoints.py
backend/protocol_rpc/server.py
frontend/src/App.vue
frontend/src/components/Simulator/NodeLogs.vue
frontend/src/stores/node.ts
frontend/src/types/store.ts

Fixes: 
- #386
- #389
- Passed the msg_handler to the consensus, node, and genvm for its use
- Captured the standard output on the execution of the intelligent contracts to show those in the UI logs
- Small fix in the frontend regarding vertical scroll
- Removed the address validation in the update validation method to prevent it from failing
- It is a feature very requested that adds important information to the development process
- Manually tested the new feature
- Ran frontend and backend tests
Add some prints to your intelligent contracts, execute them, and see those prints in the UI logs
You can now see the prints that you add to your intelligent contracts getting logged in the UI logs section.

386 sim improve logging messages during transaction execution workflow

---

backend/node/genvm/equivalence_principle.py

Fixes #395 
- Added missing return
- To fix a bug
- Tested the bug fix
N/A
Use get_webpage_with_principle in a contract
We fixed an issue when using the shortcut function get_webpage_with_principle that prevented getting a result.

395 sim fix get_webpage_with_principle return

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.vue
frontend/src/components/Simulator/ContractsPanel.vue
frontend/src/components/Simulator/HomeContractItem.vue
frontend/src/components/Simulator/HomeFeatureItem.vue
frontend/src/components/Simulator/HomeTab.vue
frontend/src/components/SimulatorMenu.vue
frontend/src/components/global/Alert.vue
frontend/src/main.ts
frontend/src/plugins/persistStore.ts
frontend/src/stores/contracts.ts
frontend/src/utils/store.ts
frontend/tailwind.config.js

Fixes #399 
- Fixed scrolling issue when overflowing content in home tab
- Improved UI/copy of home tab
- Added "open contract"  buttons
- Added erc20 example
- Added CTAs
- Fixed tooltip copy in the menu items
- Fixed a bug where "opened contracts" would remain in the local storage after being deleted, causing subsequent issues
https://github.com/user-attachments/assets/5a7c6bd5-6ba8-43a9-8011-6f6f1218abcb
- to fix the scroll issue
- to improve onboarding of users
- to fix an issue with opened contract storage causing bugs
- tested reponsive layout
- added tailwind plugin for container queries since the layout is dependent on the panel resizing
- created a dedicated component for sample contract items in home screen
- Open the simulator and play around with the …

399 sim fe scrollable home screen

---

backend/node/genvm/base.py

Partial fix for https://github.com/yeagerai/genlayer-simulator/issues/406
- It's a hotfix so that coworkers working on the hackathon can see the exceptions

hotfix: print contract init errors

---

backend/node/genvm/base.py
frontend/src/components/Simulator/ConstructorParameters.vue
frontend/src/components/Simulator/ContractMethodItem.vue
frontend/src/components/Simulator/ContractReadMethods.vue
frontend/src/components/Simulator/ContractWriteMethods.vue
frontend/src/hooks/useMockContractData.ts
frontend/src/types/index.ts
frontend/src/utils/inputs.ts
tests/integration/mocks/football_prediction_market_get_contract_schema_for_code.py
tests/integration/mocks/llm_erc20_get_contract_schema_for_code.py
tests/integration/mocks/log_indexer_get_contract_schema_for_code.py

Fixes #393 
- Fix mapping order of method params
- Because the params where getting mixed up
- used **abi** property instead of **methods** property in methods and constructors
- removed **method** property from backend response

393 sim use contract abi to generate methods and parameters

---

frontend/src/stores/transactions.ts

- added a log to identify potential race-conditions next time it happens
- to pinpoint the bug where some transactions stay on PENDING in the frontend while FINALIZED in the backend
- tested the log
Nothing special.
N/A

fix: add debug log to find out why some txs stay on pending

---

.github/workflows/release-from-main.yml

fixes https://github.com/yeagerai/genlayer-simulator/actions/runs/11361440364
with https://docs.github.com/en/enterprise-cloud@latest/actions/sharing-automations/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow

ci: inherit secrets

---

backend/database_handler/transactions_processor.py
backend/protocol_rpc/endpoints.py

Fixes #566
Described in issue
Described in issue
Manually tested by calling the endpoint with insomnia
none
There's a new RPC endpoint `sim_getTransactionsForAddress` to allow you to get all transactions for a given address

feat(rpc): add sim_getTransactionsForAddress to be able to get all transactions for a given address

---

docker/Dockerfile.webrequest
frontend/src/calldata/consts.ts
frontend/src/calldata/decoder.ts
frontend/src/calldata/encoder.ts
frontend/src/calldata/index.ts
frontend/src/components/Simulator/TransactionItem.vue
frontend/test/unit/calldata/decode.test.ts
webrequest/healthcheck.py
webrequest/server.py

Likely fixes tests + adds eq_output pretty formating. This pr will also unblock #621
- reworked healthcheck
- added calldata decoding to ts
- to fix a bug
- to improve ux
- tested by hand
- wrote small test

feat: dump eq_output transaction outputs in user friendly way in the UI

---

examples/contracts/football_prediction_market.py
examples/contracts/llm_erc20.py
examples/contracts/log_indexer.py
examples/contracts/wizard_of_coin.py
frontend/package-lock.json
tests/integration/contract_examples/mocks/football_prediction_market_get_contract_schema_for_code.py
tests/integration/contract_examples/test_football_prediction_market.py

Fixes #634 
- fixed football prediction market contract example
- added tests to check resolution data
- to check potential failures in executing a contract that calls a website
- tested the new feature
- executed integration tests
Check the new contract version regarding the access of the storage variables
Improved example contracts and integration tests

fix: contract examples with new genvm

---

.gitignore
docker/Dockerfile.webrequest

also gitignored the docker volume

fix: file permissions for webrequest.sh

---

backend/protocol_rpc/endpoint_generator.py
backend/protocol_rpc/endpoints.py
backend/protocol_rpc/message_handler/base.py
frontend/src/components/Simulator/ContractMethodItem.vue
tests/common/request.py
tests/integration/contract_examples/test_football_prediction_market.py
tests/integration/contract_examples/test_llm_erc20.py
tests/integration/contract_examples/test_log_indexer.py
tests/integration/contract_examples/test_multi_read_erc20.py
tests/integration/contract_examples/test_multi_tenant_storage.py
tests/integration/contract_examples/test_read_erc20.py
tests/integration/contract_examples/test_storage.py
tests/integration/contract_examples/test_user_storage.py

Fixes #621
- now eth_call returns base64 encoded calldata and rpc error on error
- to fix a bug
- tested the new feature manually
- integrations tests pass (except for one malformed...)

fix: rework eth_call according to spec

---

.github/workflows/docker-build-and-push-image.yml

https://genlayer.slack.com/archives/C071DE6200M/p1736448725527359
https://github.com/yeagerai/genlayer-studio/actions/runs/12708580116

ci: test fix for docker build and push

---

backend/database_handler/transactions_processor.py
backend/protocol_rpc/endpoints.py

Fixes #818 
- Raise JSONRPCError when VITE_IS_HOSTED is True for blocked endpoints
- Added a wrapper
- Added a protection for appeals to not be able to set it on True in the wrong transaction state with a CURL call
- To protect the hosted version
- Tested the new feature with CURL command
- Added a wrapper for all the methods listed in nginx/rpc-blocker.lua -> restricted_methods
- For every blocked method a call returns 
`{"error":{"code":-32000,"data":{},"message":"Non-allowed operation","name":"JSONRPCError"},"id":1,"jsonrpc":"2.0"}`
- Set code to -32000
- Set data to be empty as it does not matter because the method is blocked. If needed I can add them.
Run the studio with VITE_IS_HOSTED on True. Check the code changes.
You can use the following command:
```
curl -X POST …
```

feat: raise JSONRPCError when VITE_IS_HOSTED is True for blocked endpoints

---

backend/node/base.py
backend/node/genvm/base.py
backend/node/genvm/origin/base_host.py
docker/Dockerfile.backend
examples/contracts/log_indexer.py

Does what the title says and:
1. genvm log is now parsed for convenience
2. violating read/write rights won't fire assertion anymore

fix(genvm): update genvm version to 0.0.12

---

.github/workflows/unit-tests-pr.yml

**Pull Request: Upgrade SonarCloud GitHub Action**
**Summary:**
This pull request addresses the deprecation of the `sonarsource/sonarcloud-github-action` by migrating to the unified `sonarsource/sonarqube-scan-action`. This change ensures continued compatibility and access to the latest features for code analysis.
**Changes:**
- **Action Update:** Replaced `sonarsource/sonarcloud-github-action@v4.0.0` with `sonarsource/sonarqube-scan-action@v5.0.0` in the GitHub Actions workflow.
- **Environment Variables:** Maintained the existing `SONAR_TOKEN` configuration for authentication.
**Context:**
- **Deprecation Notice:** The `sonarsource/sonarcloud-github-action` was deprecated as of version 4.0.0. Users are encouraged to transition to the `sonarqube-scan-action` for both SonarQube Server and …

fix: Upgrade SonarCloud GitHub Action

---

frontend/src/components/Simulator/NodeLogs.vue

Fixes #985 
- Logs panel now stays scrolled to bottom when new logs get added
- Except if user had already scrolled up
This replicates expected behavior as can be seen in mot chat applications.
- Improve UX
- tested the new feature
- Used useScroll composable from vue-use library
- Improved scrolling behavior in the node logs panel

feat: node logs scrolling behavior

---

frontend/vite.config.ts

Fixes N/A - hot fix
- Adds the needed hosts to the vite configuration to support the hosted instances of the Studio
- Required by new version of VITE 6.0.0 https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#6011-2025-01-21

chore: added allowed hosts to support Studio hosted instances

---

backend/protocol_rpc/server.py

Fixes #DXP-201
- Replaced the use of `contract_snapshot_factory` with `contract_processor_factory` in the `restore_stuck_transactions` function.
- Updated the logic to use `contract_processor` instead of `contract_snapshot` for updating contract states.
- To fix a bug where the wrong factory was being used, which lead to an AttributeError.
- Started the studio with a stuck transaction.
- Decided to switch from `contract_snapshot_factory` to `contract_processor_factory` to align with the intended design and functionality.
- Focus on the changes in the `restore_stuck_transactions` function and ensure that the logic for updating contract states is correctly implemented with `contract_processor`.
- Fixed an issue in the transaction restoration process that used an old function.

fix: restore_stuck_transactions uses ContractProcessor

---

backend/node/create_nodes/default_providers/anthropic_claude-3-5-haiku-20241022.json
backend/node/create_nodes/default_providers/anthropic_claude-3-5-sonnet-20241022.json
backend/node/create_nodes/default_providers/anthropic_claude-3-7-sonnet-20250219.json
backend/node/create_nodes/providers_schema.json
frontend/src/assets/schemas/providers_schema.json

Fixes #DXP-23
- Updated Anthropic model names in the configuration files to include new models: `claude-3-5-haiku-20241022`, `claude-3-5-sonnet-20241022`, and `claude-3-7-sonnet-20250219`.
- Modified `providers_schema.json` in both backend and frontend to include these new model names.
- To ensure the application supports the latest Anthropic models, providing users with access to updated AI capabilities.
- This update aligns with the latest offerings from Anthropic, ensuring compatibility and improved performance.
- Verified that the new model configurations are correctly loaded and recognized by the system.
- Ensured that the studio can successfully interact with the new models without errors.
- Decided to keep using dates in the model names. Anthropic also supports using `-latest` …

feat: update Anthropic model names in configuration

---

.github/workflows/release-staging.yml

Added the CI BOT Token as the authorization to call the infra repo

Fix release workflow token with bot token

---

.github/workflows/release-staging.yml

Fixes #DXP-236
- changed the infra repo URL

fix: renamed infra repo

---

README.md

Fixes #613 
- telegram link for genlayer is added to readme
- to add the existing channel on telegram for visibility
- tested telegram link works

fix: add telegram link to readme

---

backend/database_handler/snapshot_manager.py

Fixes DXP-300
- Added missing field for transaction snapshot process
- to fix a bug on `load_fixture` function from genlayer-test
- Tested `load_fixture` works without problems

fix: add missing transaction fields

---

backend/node/genvm/base.py

Fixes DXP-303
-  increased genvm execution timeout to 5 minutes
- to align with real default values in protocol
- tested contract examples

refactor: increase genvm execution timeout to 5 minutes

---

backend/consensus/base.py

Fixes #DXP-46
- Added error handling around the contract registration process in the `AcceptedState` class.
- Logged errors during contract registration without interrupting the transaction processing flow.
- To improve the robustness of the contract deployment process so that the frontend's getContractSchema request will work.
- Tested in the studio.
- Focus on the error handling logic and ensure it aligns with the overall transaction processing flow.
- Improved error handling during contract registration to ensure the contract is registered in the backend when signalling to the frontend that the contract is deployed..

feat: SIM-FE-Failed contract deployments try to render schema
