consensus/algorithm.py
package-lock.json
rpc/server.py

The address calling the contract function has been passed to the exec_transaction of the consensus to avoid having to look for it in the transaction arguments

114 simulator frontend: always send from_address argument to backend calls

---

consensus/nodes/create_nodes.py
rpc/server.py

Added "exclusive providers" params to create random validators based only on that list.
The CLI requires that the validators be created only based on user selection. One option could have been to remove the ollama's models if the user doesn't select them, but that seems like it could impact other users' applications.

156-simulator---allow-to-specify-validators-provide-on-create-random-validators

---

genvm/utils.py

contract_runner was made global so it can be used in the constructor

161-simulator---use-contract-runner-in-constructor

---

.github/workflows/frontend-unit-tests.yml
.github/workflows/unit-tests-pr.yml
.github/workflows/unit-tests.yml

This only runs the frontend unit tests
The tests have triggered on opening and reopening the PR
Out of scope:
- Backend unit tests
- [Trigger from comments](https://genlayer.slack.com/archives/C071DE6200M/p1719851490588059)
- I'm still researching this approach to see if it's possible given that [some comments](https://github.com/orgs/community/discussions/25389#discussioncomment-8935283) mention it doesn't behave like PR checks

241 SIM gh-action-to-run-unit-tests-on-pr-open-and-approvals

---

backend/database_handler/validators_registry.py

While testing in staging prior to the release I was getting errors of the form
```
jsonrpc-1             | DBClient ~ ~ query: UPDATE transactions SET status = %s WHERE id = 13
jsonrpc-1             | DBClient ~ ~ params: ['PROPOSING']
jsonrpc-1             | DBClient ~ ~ query: SELECT * FROM current_state WHERE id = '0xA2Cd7eecAf8dfda72be4aBe5eB68bba96aF5b6dE' LIMIT 1
jsonrpc-1             | DBClient ~ ~ params: None
jsonrpc-1             | Error running contract 'str' object has no attribute 'items'
jsonrpc-1             | Traceback (most recent call last):
jsonrpc-1             |   File "/app/backend/node/base.py", line 76, in run_contract
jsonrpc-1             |     receipt = await self.genvm.run_contract(
jsonrpc-1             |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jsonrpc-1 …
```

Hotfix: parse validator config from string

---

docker-compose.yml

Using `latest`:
- is not reproducible, which can lead to unexpected errors
- takes time to connect to dockerhub and check for new images
I think we should manually upgrade when necessary
Downloading newer ollama images was slowing my dev flow

SIM-Pin ollama version

---

backend/database_handler/transactions_processor.py
frontend/src/plugins/persistStore.ts
frontend/src/plugins/transactionsListener.ts

This PR includes a fix for a issue when we try to get a non existing transaction
Steps to reproduce the issue:
- Create a few transactions in the simulator and stop the backend containers to keep the transactions in status PENDING
- Keep the front end running and recreate the rpc and Postgres container
- Reload the browser and then we have some transactions in the browser storage that will be used to get the transaction in the backend, then it will throw an error
After the fix:
We return `None` from the backend if the transaction not exists and then clear in the browser storage

281 SIM-Clear Latest transactions 

---

.env.example
.github/workflows/backend_integration_tests_pr.yml
backend/node/create_nodes/create_nodes.py
backend/protocol_rpc/endpoints.py
tests/integration/test_football_prediction_market.py
tests/integration/test_llm_erc20.py
tests/integration/test_storage.py
tests/integration/test_user_storage.py
tests/integration/test_wizard_of_coin.py

fixes https://github.com/yeagerai/genlayer-simulator/issues/265
- fixes e2e tests: the main reason was that we were trying to `pop` the `ollama` provider when there wasn't any in the list 
- sets gpt-3.5 as the model to use for e2e tests: this is because its way cheaper
- other small changes done along the way to keep improving the codebase little by little, following the "[boy scout rule](https://biratkirat.medium.com/step-8-the-boy-scout-rule-robert-c-martin-uncle-bob-9ac839778385)"
e2e tests were failing
e2e tests are passing in this branch
https://github.com/yeagerai/genlayer-simulator/actions/runs/9962830784

265 sim gh action to run e2e tests on pr open and approval

---

.github/workflows/docker-build-and-push-all.yml
.github/workflows/docker-build-and-push-image.yml

Fixes #319 
- Added GH Action to build and push docker images of all services
For Nakima and future use for end users
Manually created test tag:
- the GH Action ran correctly https://github.com/yeagerai/genlayer-simulator/actions/runs/10062488454
- the images are pushed in the registry https://hub.docker.com/repositories/yeagerai?search=simulator
- I've separated the workflow to be reusable for each service
- For now we are creating an image for the postgres database, which is really a small wrapper of `postgres`. In the future I think we should directly use `postgres` and configure it through volumes and envvars. Having our own thin wrapper is not very useful
Check out the links in the testing section
Container images for all services are now available at [our …

SIM-OPS-Build and Push docker images on releases

---

backend/node/create_nodes/create_nodes.py

Fixes https://github.com/yeagerai/genlayer-simulator/issues/302
- actually uses the random value from the config
- to fix a silent issue: we were not actually configuring the random values for the string cases
- ran e2e tests locally
I've decided to use `int` because it's the only type of values we have in the config
I have the SonarLint extension which is great for finding these sort of things

302 SIM fix random validator option

---

.github/workflows/backend_integration_tests_pr.yml
.github/workflows/unit-tests-pr.yml
CONTRIBUTING.md

Part of https://github.com/yeagerai/genlayer-simulator/issues/293
- Triggering tests through PR with labels `run-tests`
- I've also created the ruleset https://github.com/yeagerai/genlayer-simulator/settings/rules/1192424
- I'll enable this ruleset once this PR gets merged
In order to add checks for PRs, these checks need to be ran in the last commit of the PR (if not they are skipped, which could come as false negatives). In order to allow manual triggering of them for certain cases (like when modifications occur in the PR) I've added the functionality to trigger them with comments
- I'll add a comment to this PR to test it
The decision of using comments was done through slack

SIM-GH checks to block PRs from merging when tests don't pass #293

---

.github/workflows/release-from-main.yml

Fixes #https://github.com/yeagerai/genlayer-simulator/issues/334
- Automatically creates GH Releases from `main` branch
- to automate a manual task
- Manually called `gh release create $semver --title $semver -F body.txt --prerelease` locally and it worked as expected
I've left the `prerelease` flag since I don't have a way to test this end to end. Once we see that it works as expected I'll remove it
This PR depends on a specific format from the commits, which will go in combo with https://github.com/yeagerai/genlayer-simulator/pull/335

334 SIM-generate releases and versions when merging to main

---

frontend/src/plugins/persistStore.ts
frontend/src/views/Simulator/RunDebugView.vue

Fixes #314 
- Used store actions instead of direct store change to trigger persist plugin.
- Fixed local db query param to map to correct property.
This was an issue where the removal of transactions was not actually persisted in the local db. Deploying a new contract was simply displaying the symptom; reloading after deleting the TXs was also yielding the same result: transactions always re-appeared after removal.
- Fixed an issue were transactions were re-appearing after being cleared.

314 sim   removed transactions are restored after adds new transaction

---

.github/workflows/backend_integration_tests_pr.yml
docker/Dockerfile.backend
docker/Dockerfile.database-migration
docker/Dockerfile.webrequest

Fixes #366
- reduce backend docker image
- set PyTorch to CPU only, without NVIDIA CUDA
- also updated Python to 3.12.5
- optimize backend docker image size from 5,77GB to 1.48GB
- to fix failing CI due to no disk space left error
- tested the fix locally

366-sim-be-reduce-docker-image-by-sentence-transformers-python-package-size-optimization

---

frontend/src/stores/tutorial.ts

Could POTENTIALLY FIX #380 
- used a relative import path without '@' alias
To fix unit tests failing in GH
Can't test this locally
Need to see if unit tests now pass.

fix: use relative path for import on tutorial contract

---

.github/workflows/release-from-main.yml

Fixes https://github.com/yeagerai/genlayer-simulator/issues/334
- fix permissions for failing workflow https://github.com/yeagerai/genlayer-simulator/actions/runs/10415937465

334-SIM-generate releases and versions when merging to main

---

frontend/src/components/Simulator/CodeEditor.vue
frontend/src/components/Simulator/ConstructorParameters.vue
frontend/src/components/Simulator/ContractsPanel.vue

fixes #409 
- Fixed an issue with layout / resizing of the editor, which was causing an overlap between scrollbar and error notice
- Fixed a watcher that caused error in constructor inputs
- to fix a bug
- lint OK
- e2e OK
- unit OK
- tested the fix
- Moved the code editor initialization to a proper function instead of a watcher
- Fixed an issue where the syntax error notice was overlapping the horizontal scrollbar in the editor

fix: 409 sim fe alow horizontal scroll when there is syntax error in the contract

---

.github/workflows/conventional-commit-pr.yml
.github/workflows/only-merge-release-branches-to-main.yml
.pre-commit-config.yaml

Fixes #423 
- adds a GH action 
As @cristiam86 mentioned, we might be able to then use https://github.com/marketplace/actions/changelog-from-conventional-commits to create release notes
To adhere with our contributing standard
- pointing the PR to main doesn't trigger the workflow (needed for release PRs which are not following conventional commits)
- action has run correctly on this PR
- I've used https://github.com/ytanikin/PRConventionalCommits since it seemed to be the most maintained and with nice features
- I've removed the pre-commit hook to check conventional commits: since we are squash merging we are only interested in the PR title check

ci: gh action to validate pr title 

---

CONTRIBUTING.md

Fixes #416
- Added new considerations and workflow practices to the contributing guide
- Adapted some of the existing sections to include new practices.
- To improve the way we explain to others how to contribute in the project
- Not needed
Read it and give feedback
Updated the contributing guide to explain some new practices we have adopted to improve the development process.

docs: updated contributing

---

.github/workflows/release-from-main.yml
.gitignore
release.config.js

Fixes current cronjob github action which was not working as expected
locally tested
```
$ npx semantic-release --dry-run
[3:02:22 PM] [semantic-release] › ℹ  Release note for version 0.5.1:
* rpc endpoints (#481) (f4de409)
$ git commit --allow-empty -m "feat(a): test"
$ npx semantic-release --dry-run
[3:05:34 PM] [semantic-release] › ℹ  Release note for version 0.5.1:
* a: test (8abc883)
* rpc endpoints (#481) (f4de409)
$ git commit --allow-empty -m "feat(b): test"
$ npx semantic-release --dry-run
[3:06:10 PM] [semantic-release] › ℹ  Release note for version 0.6.0:
* b: test (6694039)
* a: test (8abc883)
* rpc endpoints (#481) (f4de409)
```
- Keep using `semantic-release`
- configured gitignore for npm in the root folder for testing locally
Fixed a bug in the release GitHub action

ci(release): fix release GitHub action

---

.github/workflows/release-from-main.yml

Releasing on weekends doesn't make sense ATM
Don't release on friday
https://i.etsystatic.com/17819941/r/il/8217b8/2348534973/il_fullxfull.2348534973_g1km.jpg
Automatic releases will be done from Monday to Thursday

ci(release): release only from Monday to Thursday

---

backend/node/genvm/equivalence_principle.py

Fixes #437 
- get_webpage_with_principle must always be comparative. For that reason, this parameter is getting removed from the method arguments.
- by definition, all get_webpage_with_principle calls should be comparative or the validator is not going to know how to agree.
- tested the prediction market contract with this shortcut function
Test this function in an intelligent contract
The comparative flag has been removed from the get_webpage_with_principle method, ensuring it is always called with the comparative flag enabled.

fix(protocol): get webpage should always be comparative

---

docker-compose.yml

Postgres 12 is reaching EoL in November
docker compose up
- chose version 16 since it's the latest, with the longest support
!!! this will re-create the container, making user's lose all their data
I don't think there's 
If you had the volume set, I recomment you to destroy it. 
There are ways to save the content if you like https://hollo.me/devops/upgrade-postgresql-database-with-docker.html
Upgrade Postgres from version 12 to 16

chore(postgres): upgrade Postgres from version 12 to 16

---

.github/workflows/frontend-unit-tests.yml
.github/workflows/test-sonarqube.yml
sonar-project.properties

jobs were failing https://github.com/yeagerai/genlayer-simulator/actions/runs/10853398354/job/30121579703
Also run it on pull requests to see code quality diffs
Taken from https://sonarcloud.io/project/information?id=yeagerai_genlayer-simulator
ci: Fixed SonarCloud organization key

ci(sonarcloud): fix organization name

---

.github/workflows/.pre-commit.yml
.github/workflows/backend_integration_tests_pr.yml
.github/workflows/unit-tests-pr.yml
.pre-commit-config.yaml
sonar-project.properties

- separate unit from load tests 
- remove pytest from pre-commit
- run unit tests in main (to fix [this codecov banners](https://github.com/yeagerai/genlayer-simulator/pull/525#issuecomment-2359184426))
To have better experience with CI
I took the liberty to create this fix on my own since I felt that some parts of our CI were not working as expected, reducing my productivity
let's check the CI of this PR
N/A

ci: separate unit from load tests and remove pytest from pre-commit

---

docker/Dockerfile.backend
docker/Dockerfile.database-migration
docker/Dockerfile.webrequest

uses buildkit cache mounts to try to reuse pip cache
by updating regularly the requirements.txt, we are invalidating the cache a lot
smoke tested locally
The biggest package by far is `sentence-transformers`
Should we decouple the requirements.txt into many files? 
- ATM the requirements.txt also has testing packages
- separating the files would improve cache
learn about buildkit cache
You'll now get faster build times by leveraging the power of buildkit's cache

chore(docker): improve pip cache with buildkit

---

backend/protocol_rpc/endpoint_generator.py
tests/integration/contract_examples/test_llm_erc20.py
tests/unit/test_endpoint_generator.py

Fixes #404
- serializes results from the backend to be json compatible
- to handle more result types like tuples in IContracts
Tested manually this contract:
```py
from backend.node.genvm.icontract import IContract
class TTT(IContract):
def __init__(self):
pass
def get_test(self):
return 1, "test", 1, True, [1, (False)]
```
- Created custom serialize function instead of importing another package to serialize objects
- I wanted to use the serialization of flask-jsonrpc, but I couldn't find its API
Test it out manually
Now you can use Python tuples in your Intelligent Contracts outputs

fix(jsonrpc): serialize result objects

---

.env.example
docker/Dockerfile.webrequest
frontend/vite.config.ts
frontend/vitest.config.ts

Fixes #476
Superseeds https://github.com/yeagerai/genlayer-simulator/pull/538
Allows configuring proxy for the frontend to the backend with the following configuration 
```
VITE_PROXY_ENABLED = 'true'
VITE_JSON_RPC_SERVER_URL  = '/api'
VITE_WS_SERVER_URL='/' 
```
This envvars need to be present in the frontend build process. For example, by adding them in your `.env` file
- to allow a new deployment architecture
tested standard and new configuration. Both api and websockets worked correctly
I have created this pr to superseed https://github.com/yeagerai/genlayer-simulator/pull/538 because I feel is faster. Nothing to do with how @rekpero worked, just a matter of process  
---
It's possible to automatically configure everything from `VITE_PROXY_ENABLED`, but that would require adding a …

feat(fe): proxy to jsonrpc

---

.github/workflows/docker-build-and-push-all.yml
.github/workflows/release-from-main.yml

Fixes the problem that tags are not being pushed to docker hub
To get the images into dockerhub, I want to use them in other projects
None
I could've used PATs as mentioned [here](https://github.com/orgs/community/discussions/25702), but 
- I couldn't create a PAT for this repo (not enabled by the yeagerai org probably)
- I think it's a "magic" solution. I like it better written explicitly
N/A

ci: fix tags not getting pushed to dockerhub

---

.env.example
backend/protocol_rpc/server.py
backend/protocol_rpc/validators_init.py
docker/Dockerfile.backend
tests/integration/test_llm_providers_registry.py
tests/unit/test_validators_init.py

Fixes #567
Allows configuring validators from the envvar `VALIDATORS_CONFIG_JSON`
To make deployment easier
- unit tests
- tested with `VALIDATORS_CONFIG_JSON = '[{"stake": 100, "provider": "openai", "model": "gpt-4o", "amount": 2}]'` and `VALIDATORS_CONFIG_JSON = ''`
- I did it in the same component as the jsonrpc server so that we don't need a new component, which would make deployment more complex
- I didn't use threads to do it since it doesn't take much time, and also threading would've made it more complex given that exception handling across threads is hard
Read unit tests first to understand the behavior
Maybe this feature is useful in the genlayer CLI? @denishacquin @cristiam86 
Now you can easily start up your validators from the envvar `VALIDATORS_CONFIG_JSON`

feat: allow configuring validators from envvar

---

frontend/src/components/Simulator/ContractInfo.vue
frontend/src/hooks/useContractQueries.ts

Fixes #495 
- Fixed the issue by removing deployed contract from store on deploy, effectively hiding methods UI when a new deployment is triggered
- Improved "new deployment" button icon/copy for clarity:
- to fix a bug
- to improve UX
- frontend e2e ok
- frontend unit ok
- Decided to improve some copy
- Validate that the copy makes sense for the button
- Fixed an issue with contract method not pointing to the correct contract instance during deployment

fix: hide methods during deployment to avoid pointing to the wrong contract instance

---

docker/Dockerfile.database-migration

Now the database migration image is smaller, improving build times

chore: reduce dependencies from database-migration docker image

---

backend/consensus/base.py
backend/node/base.py
backend/protocol_rpc/message_handler/base.py
backend/protocol_rpc/message_handler/types.py
examples/contracts/wizard_of_coin.py
frontend/src/components/Simulator/ContractMethodItem.vue
frontend/src/hooks/useConfig.ts
frontend/src/stores/contracts.ts
frontend/src/stores/transactions.ts
frontend/src/views/Simulator/SettingsView.vue
frontend/test/unit/stores/contracts.test.ts
frontend/test/unit/stores/transactions.test.ts

- Fixes **event logs sent across users on hosted environment** (the issue appeared with the genvm integration; we were not tracking the client session id on genvm/consensus-related events anymore, effectively dispatching them to all clients. To fix this, I added the transaction hash-scoping to those events as well).
- **Adds a loading state on call method buttons** (wasn't needed before because it was instant; now that the call takes a bit of time it's better for ux responsiveness to set the button to a loading state while the call is processing).
- **Hide provider settings** when on hosted environment
- Fixes **transaction async data errors and inconsistencies** (specifically: handling the case where a server tx doesn't exists anymore after a db reset properly and clearing local txs if …

fix: cross-client event logs on hosted env, tx async data inconsistencies

---

.github/workflows/docker-build-and-push-image.yml

- Updated the GitHub Actions workflow to enable multi-platform support for Docker images.
- Added `platforms: linux/amd64,linux/arm64` to the `docker/build-and-push-image` step.
- Ensured the workflow builds and pushes images for both `amd64` and `arm64` architectures to the Docker registry.
- To support both x86-based and ARM-based systems (e.g., Apple Silicon and ARM servers).
- This ensures broader compatibility for users and developers running the simulator on different architectures.
- Verified that images build successfully for both `amd64` and `arm64` platforms using `docker buildx build`.
- Inspected the generated image manifests to confirm both architectures are included.
- Confirmed the workflow runs as expected without breaking existing functionality.
- Decided to update only …

feat: adding ARM64

---

.github/workflows/release-from-main.yml

Fixes #651
- Added `workflow_dispatch` trigger to the "Create releases from main every day" workflow, allowing manual execution of the workflow.
- Retained the existing `cron` schedule for automatic execution.
- To provide flexibility to trigger the release workflow manually when needed, such as for urgent releases or testing.
- Ensures developers can bypass the scheduled timing without making code changes to the workflow.
- Manually triggered the workflow via the **Actions** tab to verify the new `workflow_dispatch` trigger works correctly.
- Confirmed that the latest changes from the `main` branch were included in the run.
- Validated that all steps (release creation and Docker image push) executed successfully without errors.
- Kept the existing `cron` schedule untouched to ensure the …

feat: workflow_dispatch Trigger

---

.github/workflows/docker-build-and-push-image.yml

Fixes #601 
- Updated the `docker-build-and-push-image.yml` workflow to include semantic versioning for Docker tags alongside the `latest` tag.
- Modified the `docker/metadata-action` step to use `type=semver,pattern={{version}}` and `type=raw,value=latest` for consistent tagging.
- Ensured local testing compatibility by setting `push: false` in the `docker/build-push-action` during testing.
- To ensure Docker images are tagged with both `latest` and semantic versions (e.g., `0.26.0`), improving traceability and version control for image consumers.
- Simulated a Git tag trigger (`v0.26.0`) using `act` to verify correct image tagging (`latest` and `0.26.0`).
- Built and tagged images locally without pushing to Docker Hub.
- Decided to use `type=semver,pattern={{version}}` to extract …

feat: generating tags with semver

---

.github/workflows/docker-build-and-push-image.yml

Fixes #686 
- Implemented logic to dynamically fetch the latest Git tag for use in Docker image tagging.
- Updated the workflow to use the fetched tag 
- To ensure that Docker images are consistently tagged with the most recent Git tag, improving traceability and alignment with the repository's versioning strategy.
- Adds more flexibility and reliability to the workflow by using Git's tag history.
- Tested the solution by triggering the workflow directly from my `686-not-pushing-version-when-the-release-workflow-is-called-using-schedule` branch using GitHub CLI.
- The successful runs can be observed in the Actions history under this branch.
- Decided to fetch the most recent Git tag dynamically instead of relying on `package.json` or fixed tags for better traceability.
- Focus on the `git …

feat: pushing version when workflow is called using schedule

---

frontend/src/hooks/useGenlayer.ts

Fixes #699 
- pass the endpoint for genlayer RPC
- to have calls going through genlayer-js working on both environments
- Fixed genlayer-js RPC calls in hosted studio

fix: adapt endpoint for genlayer js rpc

---

.github/workflows/docker-build-and-push-all.yml

Fixes #692 
- Added a `hardhat` step to the GitHub workflow to build and push a Docker image for the Hardhat service.
- Configured the step to use the `docker-build-and-push-image.yml` reusable workflow with appropriate parameters:
- `docker_build_context`: `.`
- `dockerfile`: `docker/Dockerfile.hardhat`
- `dockerhub_repo`: `yeagerai/simulator-hardhat`
- `dockerhub_username`: `${{ vars.DOCKERHUB_USERNAME }}`
- `dockerhub_token`: `${{ secrets.DOCKERHUB_TOKEN }}`
- To address the issue of missing Hardhat Docker images in the registry.
- To ensure the Hardhat service is available for CLI and dependent services, aligning it with other Studio services.
- Verified workflow syntax locally.
- Confirmed similar jobs for other services (e.g., `jsonrpc`, `frontend`) function as expected using the …

fix: adding Hardhat Dockerfile in GitHub Workflow

---

docker-compose.yml
docker/Dockerfile.hardhat

- Added healthcheck to hardhat service in docker-compose.yml to verify node availability
- Modified Dockerfile.hardhat to ensure contracts are deployed after node is ready
- Added proper service dependency in docker-compose.yml to ensure jsonrpc waits for hardhat
- Added healthcheck script directly in Dockerfile to maintain Windows compatibility
A race condition was causing the jsonrpc service to attempt accessing hardhat accounts before they were available. This would cause:
- Failed transaction insertions due to unavailable accounts
- Finality window crashes with inability to recover
- Inconsistent contract deployment state
Fixes #702 
- Tested multiple `docker compose up` cycles to verify consistent initialization
- Verified hardhat node is fully ready before jsonrpc attempts …

fix(hardhat): prevent race conditions in contract deployment

---

.env.example

Fixes #706
- Added BACKEND_BUILD_TARGET used in docker compose file in .env.example file
- Somehow this variable was not set which means the code was always running in production mode
- To add more value to the developer
- Tested the bug fix by reloading the localhost webpage with a python change and seeing the changes behaviour happening
Make code changes and see if the hot reload works.
Added BACKEND_BUILD_TARGET in .env for hot reload of the backend

fix: add BACKEND_BUILD_TARGET in .env

---

.env.example
backend/consensus/base.py
backend/protocol_rpc/endpoints.py
backend/protocol_rpc/server.py
frontend/src/hooks/useConfig.ts
frontend/src/services/IJsonRpcService.ts
frontend/src/services/JsonRpcService.ts
frontend/src/stores/node.ts
frontend/src/views/Simulator/RunDebugView.vue

Fixes #710
- Added a field to the frontend to change the finality window of the appeal process
- To add more value to the user
- Tested the new feature on the webpage
I have put the field below the leader. Let me know if it is better to put it in the settings tab.
See code changes and run the studio.
A number field is added to the frontend to change the finality window of the appeal process.

feat: add number input for finality window

---

backend/consensus/base.py

Fixes #766 
- Added arguments to exec_transaction_with_session_handling() because tasks are created containing variables outside of the task function. The value of the variable transaction changes because of the for loop. So the created tasks point to the same transaction which won't let the system run the tasks in parallel. Passing the transaction instead of using the local variable solves this behaviour, see screenshots.
- To fix a bug and make it more user friendly
- Tested the bug fix in the localhost
I was thinking of making other threads for each contract pending queue but passing the variable solved it.
Run the code, check the code changes
For every contract, the transactions get processed sequentially. But between contracts, the transactions are processed in parallel.

fix: consensus pending queue runs sequentially

---

docker/Dockerfile.hardhat

Fixes #792 
- Added a step in the `Dockerfile.hardhat` to pre-download the Solidity compiler during the build process.
- To improve container startup performance by reducing the time spent downloading and compiling Solidity contracts at runtime.
- Enhances developer experience by ensuring the environment is preconfigured.
- Built the Docker image and verified that the Solidity compiler is pre-downloaded during the build step.
- Verified that the container starts without downloading the compiler again
- Successfully deployed contracts using the updated Docker image
- Decided to preinstall the compiler is to simplify the process and improve image portability.
- Focus on the `RUN npx hardhat compile || true` addition in the `Dockerfile.hardhat`.
- Verify the change aligns with the goal of …

fix(hardhat): preinstall solidity compiler to speed up container startup

---

backend/protocol_rpc/endpoints.py

Fixes #838
Only fixes the issue's problem
I am using VALIDATORS_CONFIG_JSON and I need it
Tested changing VALIDATORS_CONFIG_JSON and it works
We should probably do this with all of the functions
I think there's a problem with the current model: we have mixed our domain logic and our endpoints logic
I think it'd be nice if we were able to extract the logic into it's own module, and then import it from the flask server and expose what we want
Obviously this is a larger issue what I'm fixing here
Fix bug with `VALIDATORS_CONFIG_JSON`

fix: only forbid endpoint, not function

---

tests/db-sqlalchemy/transactions_processor_test.py

Fixes #842
- Changed the patch and mock for eth.accounts
- To fix a bug in the test
- Tested the bug fix by running the failed test
Fixed the code so the test won't fail. I guess insert_transaction() will change in the future so this patch might be removed or not.
Run test locally: POSTGRES_URL=postgresql://postgres:postgres@localhost:5432/genlayer_state PYTHONPATH=$PWD pytest tests/db-sqlalchemy/transactions_processor_test.py
db-integration-test works again

fix: db-integration-test contains mock error

---

backend/database_handler/transactions_processor.py

Fixes #863 
- Modified block hash and timestamp handling in `transactions_processor.py` to handle empty transaction lists
- Changed default block hash to be zeros instead of accessing first transaction
- Updated timestamp logic to handle cases with no transactions
- To fix a bug where the processor would return None when no transactions exist
- To provide consistent behavior with default values when processing empty transaction lists
- To prevent potential IndexError when accessing transaction timestamps with empty lists
- Tested transaction processing with empty transaction lists
- Verified default values are correctly set when no transactions exist
- Confirmed existing functionality still works with non-empty transaction lists
- Used "0x" + "0" * 64 as the default block hash to maintain …

fix: return dummy information for metamask compatibility

---

docker-compose.yml
traefik.yaml

Fixes #880 
- Replaced NGINX with Traefik v3.2 as reverse proxy
- Added Traefik configuration and labels for frontend/jsonrpc services
- Simplified SSL/TLS handling through Traefik
- To modernize proxy infrastructure
- To leverage Traefik's automatic service discovery and routing
- To simplify configuration and maintenance
- Verified frontend and API routing works correctly
- Confirmed TLS termination functions properly
- Tested service discovery with multiple jsonrpc replicas
Updated reverse proxy from NGINX to Traefik v3.2 for improved service management. No user-facing changes expected.

chore: replaced nginx with traefik

---

docker-compose.yml

Fixes #N/A
- Added `/socket.io` path to Traefik routing rule for jsonrpc service
- To enable WebSocket connections through the `/socket.io` endpoint
- To maintain compatibility with Socket.IO client connections
- Verified WebSocket connections work through Traefik
- Confirmed existing API routes continue to function
Added WebSocket support through Socket.IO endpoint in the API service.

chore: added socketio path in jsonrpc service

---

frontend/src/components/Simulator/ContractInfo.vue
frontend/src/components/Simulator/TransactionsList.vue
frontend/src/hooks/index.ts
frontend/src/hooks/useContractListener.ts
frontend/src/hooks/useContractQueries.ts
frontend/src/hooks/useMockContractData.ts
frontend/src/hooks/useSetupStores.ts
frontend/src/stores/node.ts
frontend/src/stores/transactions.ts
frontend/src/views/Simulator/RunDebugView.vue
frontend/test/unit/hooks/useContractListener.test.ts

Fixes #893 
- **Fixed deployment flow**; We were listening to a transaction event which was unreliable and moreover did not carry the contract address in its payload anymore, resulting in an error when subsequently fetching the contract abi. We are now listening to a dedicated **deployed_contract** event instead.
- **Fixed broken tutorial**: when 0 validators, some conditions in the templates were hiding the sections with contract constructor and methods, resulting in a broken tutorial. Added relevant adding exceptions in the UI to handle this edge case. Furthermore, the tutorial was broken because the mock data we were using didn't match the structure of the payloads of contracts anymore, so I update the mock data to reflect it.
- **Fixed transaction store persister race condition**: …

fix: deploy event and tutorial error

---

backend/consensus/base.py

Fixes #969 
- Updated the logic in `ConsensusAlgorithm` to correctly count used leaders in the consensus check.
- To fix a bug where the consensus check did not account for used leaders so the error is not caught.
- Verified that the updated condition correctly counts both validators and used leaders in UI.
- Decided to use the `get_used_leader_addresses_from_consensus_history` method to retrieve used leader addresses, as it provides a reliable way to access this information from the transaction's consensus history.
- Pay attention to the logic change in the consensus check condition to ensure it aligns with the intended behavior.
- Fixed an issue in the consensus algorithm where used leaders were not counted in the consensus check.

fix: appeals bug leader appeal no validators check

---

backend/consensus/base.py

Fixes #981 
- Updated the `ConsensusAlgorithm` and various `TransactionState` classes to use a stored contract snapshot for leader appeals.
- Introduced a check to determine if a contract snapshot is already stored before creating a new one.
- Utilized `deepcopy` to ensure the integrity of the contract snapshot when it already exists. So that a validator does not use a modified version.
- Added logic to save the contract snapshot for potential future appeals.
- To fix a bug where leader appeals were not using the stored contract snapshot, which led to inconsistencies in transaction processing.
- Verified that the system correctly uses the stored contract snapshot during leader appeals in UI.
- Decided to use `deepcopy` for existing contract snapshots to prevent unintended modifications.
- …

fix: appeal leader appeal uses wrong contractsnapshot

---

.cursor/mcp.json

Fixes #1023 
- Added a new configuration file `.cursor/mcp.json` to the project.
- This file defines an MCP server configuration for PostgreSQL using Docker.
- To enable easy setup and management of a PostgreSQL server using Docker.
- This change facilitates development and testing by providing a consistent environment.
- Verified that the Docker command specified in the configuration runs successfully.
- Ensured that the PostgreSQL server is accessible and operational as expected.
- Performed a cursor prompt to access the database:
- Decided to use Docker for managing the PostgreSQL server to leverage containerization benefits.
- Chose to use the `host` network mode for simplicity in accessing the database.
- Go to Cursor Settings -> MCP and see if it is running (green circle).
- Review …

feat: cursor add MCP server file for postgres db

---

backend/database_handler/transactions_processor.py

fix: add default consensus history object for old transactions

---

backend/consensus/base.py
backend/database_handler/transactions_processor.py
backend/protocol_rpc/server.py
tests/unit/consensus/test_helpers.py
webrequest/llms.py

Fixes #DXP-242
- Made status argument option in the method `previous_transaction_with_status` to reuse it and renamed it to `get_previous_transaction` in `transactions_processor`.
- Updated the logic in `ConsensusAlgorithm` to handle processing activated transactions more robustly by checking various conditions on the previous transaction.
- To ensure that the consensus algorithm correctly handles transactions based on their status, preventing potential errors in state transitions.
- Tested the consensus algorithm to ensure it correctly processes transactions with the new logic.
- Decided to replace the existing method with a more flexible one to accommodate future needs for transaction retrieval.
- Focus on the changes.
- Enhanced the consensus algorithm to handle transactions more …

fix: avoid activating new transactions when the previous one is not accepted

---

backend/consensus/base.py
tests/unit/consensus/test_base.py

Fixes #DXP-258
- Changed the handling of binary calldata to use base64 encoding instead of UTF-8 decoding
- Modified transaction hash handling to use provided hash from receipt or generate a new one if not available
- To properly handle binary data in contract messages that may contain non-UTF-8 characters
- To ensure transaction hashes are always available, even when not provided in the receipt
- To prevent potential decoding errors when processing contract messages
- Verified that binary calldata is properly encoded as base64
- Confirmed that transaction hashes are correctly assigned from receipt or generated when needed
- Tested contract message processing with various data types

fix: generate contracts address when consensus_service is not running

---

frontend/package.json

chore: fixing genlayer-js version

---

backend/database_handler/validators_registry.py
backend/protocol_rpc/endpoints.py
tests/db-sqlalchemy/validators_registry_test.py

Fixes #DXP-289
- Updated the `to_dict` function in `validators_registry.py` to include an optional `include_private_key` parameter, allowing control over whether the `private_key` is included in the dictionary representation of a `Validator`.
- Modified the `get_all_validators` and `get_validator` methods in `ValidatorsRegistry` to accept the `include_private_key` parameter, providing flexibility in returning validator data with or without the private key.
- Updated the `create_validator` and `update_validator` methods to exclude the private key from the returned dictionary by default.
- Adjusted the `get_all_validators` and `get_validator` functions in `endpoints.py` to call the updated methods with `include_private_key=False`. So frontend and rpc calls won't have the private key.
- To …

fix: remove private_key from validators for endpoints methods

---

backend/protocol_rpc/endpoints.py

Fixes DXP-310
- Added check forbidden to the snapshots endpoints
- sim_createSnapshot
- sim_restoreSnapshot
- sim_deleteAllSnapshots
- It was intended to be a feature for local development
- `sim_restoreSnapshot` can cause integrity errors in contract state data
- Tested that currently, any user can call snapshot endpoints on the hosted studio
- Used `check_forbidden_method_in_hosted_studio`  wrapper to block endpoints in hosted studio

fix: make snapshots endpoints to be forbidden in hosted studio

---

.github/workflows/release-staging.yml

Fixes #DXP-431
- Changed the `curl` command to use the `-L` flag for following redirects.
- Updated the GitHub repository URL from `yeagerai` to `genlayerlabs`.
- To ensure the `curl` command follows redirects, which is necessary for successful API requests.
- To correct the repository URL, ensuring the deployment triggers the correct workflow.
Manually triggered Release staging https://github.com/genlayerlabs/genlayer-studio/actions/runs/15969771831 which triggered https://github.com/genlayerlabs/genlayer-infra/actions/runs/15969773614
Focus on the changes to the `curl` command and ensure the repository URL is correct.
Improved the deployment process by ensuring API requests target the correct repository.

fix: Fix Studio Stage deployment
